project:
  type: website
  output-dir: docs

website:
  title: "The Leap Blog"
  navbar: false

format:
  html:
    theme: 
      - default
    css: styles.css
    include-before-body: _partials/header.html
    toc: false
    mainfont: "Inter"
    fontfamily: sans-serif
    code-fold: false
    code-tools: false
    link-external-newwindow: true
    comments:
      giscus:
        repo: xKDR/The-Leap-Blog
        repo-id: "YOUR_REPO_ID"
        category: "Announcements"
        category-id: "YOUR_CATEGORY_ID"
        mapping: pathname
        reactions-enabled: true
        loading: lazy
        input-position: bottom
        theme: light
